### ISSUE TITLE
visualize: Improve Terminal Top bar

### ISSUE THREAD

**Issue by gabru-md** [yogdaan/git-from-scratch#12]
Make the terminal top bar more realistic.
Add some fake buttons etc to make it look more like a terminal

:)

**Comment by aashutoshrathi** [comment]
Isn't it fixed?

**Comment by gabru-md** [comment]
oh yes it is!

**Comment by gabru-md** [comment]
we've shifted to react.There are many issues open for typescript, I guess all of them needs to be closed
