### ISSUE TITLE
Front End Stack

### ISSUE THREAD

**Issue by ParthS007** [yogdaan/git-from-scratch#19]
React with thumbs +1 or thumbs down -1 we can decide the stack.

**Comment by ParthS007** [comment]
Angular

**Comment by ParthS007** [comment]
React

**Comment by gabru-md** [comment]
This issue can be closed.
And since no one has send a PR for REACT Conversion from the past 2 weeks, Therefore the project will now be carried on using Angular Only.

Thank you everyone
